name: Prod workflow

on:
  push:
    branches:
      - main

env:
  FRONT_IMAGE: ghcr.io/${{ github.repository }}/front_prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.17
        uses: actions/setup-node@v3
        with:
          node-version: '14.17'
      - name: Install npm
        run: npm install
        env:
          CI: true
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: ${{ env.FRONT_IMAGE }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile.prod
          tags: latest
      - name: Add environment variables to .env
        run: |
          echo FRONT_IMAGE=${{ env.FRONT_IMAGE }} > .env_front

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_IP_ADDRESS }}
          port: ${{ secrets.PROD_SSH_PORT }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_USERPW }}
          source: ".env_front,docker_compose_frontprod.yml"
          target: "/home/${{ secrets.PROD_USERNAME }}"

      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_IP_ADDRESS }}
          port: ${{ secrets.PROD_SSH_PORT }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_USERPW }}
          script: |
            cd /home/${{ secrets.PROD_USERNAME }}
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ${{ env.FRONT_IMAGE }}
            docker compose --env-file .env_front -f docker_compose_frontprod.yml up -d
